import "server-only"
import fs from "node:fs"
import path from "node:path"

/**
 * Runtime environment.
 *
 * Dispatch is configured almost entirely from the admin panel. The only
 * required environment variable is `DOMAIN` (e.g. `mail.example.com`).
 * Everything else has a sensible default so `docker compose up` just works.
 *
 * Optional overrides (advanced):
 *  - APP_URL             full public URL (default: https://$DOMAIN, http://localhost:3000 in dev)
 *  - DATABASE_URL        external Postgres (default: bundled db service)
 *  - DATA_DIR            persistent data dir (default: /data in Docker, ./.data locally)
 *  - DISPATCH_SECRET     master encryption secret (default: auto-generated in $DATA_DIR/secrets)
 */
export const isProd = process.env.NODE_ENV === "production"

export function getDataDir() {
  const dir = process.env.DATA_DIR || (fs.existsSync("/data") ? "/data" : path.join(process.cwd(), ".data"))
  fs.mkdirSync(dir, { recursive: true })
  return dir
}

export function getAppUrl(): string {
  if (process.env.APP_URL) return process.env.APP_URL.replace(/\/$/, "")
  const domain = process.env.DOMAIN?.trim()
  if (domain) {
    if (/^https?:\/\//.test(domain)) return domain.replace(/\/$/, "")
    const local = domain.startsWith("localhost") || domain.startsWith("127.0.0.1")
    return `${local ? "http" : "https"}://${domain}`
  }
  return `http://localhost:${process.env.PORT || 3000}`
}

export function getDomain(): string {
  return new URL(getAppUrl()).host
}

export function isSecureContext(): boolean {
  return getAppUrl().startsWith("https://")
}

function readSecretFile(file: string): string | undefined {
  try {
    return fs.readFileSync(file, "utf8").trim() || undefined
  } catch {
    return undefined
  }
}

/**
 * Database URL resolution order:
 *  1. DATABASE_URL
 *  2. bundled docker-compose Postgres (password generated by the db container
 *     into the shared secrets volume at /secrets/db_password)
 *  3. local development default
 */
export function getDatabaseUrl(): string {
  if (process.env.DATABASE_URL) return process.env.DATABASE_URL
  const secretsDir = process.env.SECRETS_DIR || "/secrets"
  const pw = readSecretFile(path.join(secretsDir, "db_password"))
  if (pw) {
    const host = process.env.DB_HOST || "db"
    return `postgres://dispatch:${encodeURIComponent(pw)}@${host}:5432/dispatch`
  }
  return "postgres://dispatch:dispatch@localhost:5432/dispatch"
}
